name: CI/CD Pipeline

on:  
  push:  
    branches:  
      - main  # Pipeline akan berjalan saat ada push ke branch main  
  pull_request:  
    branches:  
      - main  # Pipeline juga berjalan saat ada pull request ke main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
